version: 2.0

#### YAML ANCHORS INSTEAD OF COMMANDS # while version 2.1 already supports commands, the local runner doesn't. When it does, we can upgrade.

git-submodules: &git-submodules
  run:
    name: "Pull Submodules"
    command: |
      git submodule init
      git submodule update

store-junit-results: &store-junit-test-results
  store_test_results:
    path: tmp/junit

store-test-artifacts: &store-test-artifacts
  store_artifacts:
    path: tmp/junit
    destination: junit

restore-caches: &restore-caches
  restore_cache:
    keys:
      - 3scale-system-bundler-{{ .Branch }}-{{ checksum "Gemfile" }}
      - 3scale-system-npm-{{ .Branch }}-{{ checksum "package.json" }}
      - 3scale-system-apicast-{{ .Branch }}





jobs:
  deps_bundler:
    machine: true
    steps:
      - checkout
      - *git-submodules
      - run:
          name: Install gems with bundler
          command: make bundle-in-container
      - save_cache:
          key: 3scale-system-bundler-{{ .Branch }}-{{ checksum "Gemfile" }}
          paths:
            - $CIRCLE_WORKING_DIRECTORY/vendor/bundle
  deps_npm:
    machine: true
    steps:
      - checkout
      - *git-submodules
      - run:
          name: Install NPM dependencies
          command: make npm-install-in-container
      - save_cache:
          key: 3scale-system-npm-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - $CIRCLE_WORKING_DIRECTORY/node_modules
            - $CIRCLE_WORKING_DIRECTORY/assets/jspm_packages
#          - $CIRCLE_WORKING_DIRECTORY/.config/yarn/global
  deps_apicast:
    machine: true
    steps:
      - checkout
      - *git-submodules
      - run:
          name: Install Apicast dependencies
          command: make apicast-dependencies-in-container
      - save_cache:
          key: 3scale-system-apicast-{{ .Branch }}
          paths:
            - $CIRCLE_WORKING_DIRECTORY/vendor/docker-gateway/.luarocks


  test1:
    machine: true
    steps:
      - checkout
      - *git-submodules
      - *restore-caches
      - run:
          name: Run tests 1
          command: MULTIJOB_KIND=1 make test
      - *store-junit-test-results
      - *store-test-artifacts

  test2:
    machine: true
    steps:
      - checkout
      - *git-submodules
      - *restore-caches
      - run:
          name: Run tests 2
          command: MULTIJOB_KIND=2 make test
      - *store-junit-test-results
      - *store-test-artifacts

  test3:
    machine: true
    steps:
      - checkout
      - *git-submodules
      - *restore-caches
      - run:
          name: Run tests 3
          command: MULTIJOB_KIND=3 make test
      - *store-junit-test-results
      - *store-test-artifacts

  test4:
    machine: true
    steps:
      - checkout
      - *git-submodules
      - *restore-caches
      - run:
          name: Run tests 4
          command: MULTIJOB_KIND=4 make test
      - *store-junit-test-results
      - *store-test-artifacts

  test5:
    machine: true
    steps:
      - checkout
      - *git-submodules
      - *restore-caches
      - run:
          name: Run tests 5
          command: MULTIJOB_KIND=5 make test
      - *store-junit-test-results
      - *store-test-artifacts

  test6:
    machine: true
    steps:
      - checkout
      - *git-submodules
      - *restore-caches
      - run:
          name: Run tests 6
          command: MULTIJOB_KIND=6 make test
      - *store-junit-test-results
      - *store-test-artifacts

  licenses:
    machine: true
    steps:
      - checkout
      - *git-submodules
      - *restore-caches
      - run:
          name: Run tests 7
          command: PROXY_ENABLED=1 MULTIJOB_KIND=licenses make test
      - *store-junit-test-results
      - *store-test-artifacts

workflows:
  version: 2
  parallel_build:
    jobs:
      - deps_bundler
      - deps_npm
      - deps_apicast

#      - test1:
#          requires:
#            - deps_bundler
#            - deps_npm
#            - deps_apicast
      - test2:
          requires:
            - deps_bundler
            - deps_npm
            - deps_apicast
#      - test3:
#          requires:
#            - deps_bundler
#            - deps_npm
#            - deps_apicast
#      - test4:
#          requires:
#            - deps_bundler
#            - deps_npm
#            - deps_apicast
#      - test5:
#          requires:
#            - deps_bundler
#            - deps_npm
#            - deps_apicast
#      - test6:
#          requires:
#            - deps_bundler
#            - deps_npm
#            - deps_apicast
#      - licenses:
#            requires:
#              - deps_bundler
#              - deps_npm
#              - deps_apicast
