version: 2.0

#### YAML ANCHORS INSTEAD OF COMMANDS # while version 2.1 already supports commands, the local runner doesn't. When it does, we can upgrade.

git-submodules: &git-submodules
  run:
    name: "Pull Submodules"
    command: |
      git submodule init
      git submodule update

store-junit-results: &store-junit-test-results
  store_test_results:
    path: tmp/junit

store-test-artifacts: &store-test-artifacts
  store_artifacts:
    path: tmp/junit
    destination: junit

restore-bundler-cache: &restore-bundler-cache
  restore_cache:
    keys:
      - v1-bundler-gems-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
restore-npm-cache: &restore-npm-cache
  restore_cache:
    keys:
      - v1-npm-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
#restore-gateway-cache: &restore-gateway-cache
#  restore_cache:
#    keys:
#      - v1-gateway-{{ arch }}-{{ .Branch }}-{{ .Revision }}



attach-to-workspace: &attach-to-workspace
  attach_workspace:
    at: .

jobs:
  dependencies_bundler:
    docker:
      - image: quay.io/gsaslis/3scale-system-builder
    steps:
      - checkout
      - *git-submodules
      - *restore-bundler-cache
      - run:
          name: Install gems with bundler
          command: make bundle
      - save_cache:
          key: v1-bundler-gems-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
            - ./.bundle/
  dependencies_npm:
    docker:
      - image: quay.io/gsaslis/3scale-system-builder
    steps:
      - checkout
      - *git-submodules
      - *restore-npm-cache
      - run:
          name: Install NPM dependencies
          command: make npm-install
      - save_cache:
          key: v1-npm-{{ arch }}-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./assets/jspm_packages
            - ./.jspm

  #  dependencies_apicast:
#    docker:
#      - image: quay.io/gsaslis/3scale-system-builder
#    steps:
#      - checkout
#      - *git-submodules
#      - *restore-gateway-cache
#      - run:
#          name: Install Apicast dependencies
#          command: make apicast-dependencies
#      - save_cache:
#          key: v1-gateway-{{ arch }}-{{ .Branch }}-{{ .Revision }}
#          paths:
#            - ./vendor/docker-gateway/.luarocks
  assets_precompile:
    docker:
      - image: quay.io/gsaslis/3scale-system-builder
    steps:
      - checkout
      - *git-submodules
      - *restore-bundler-cache
      - *restore-npm-cache
      - run:
          name: Precompile assets
          command: |
            cp config/examples/*.yml config/
            make precompile-assets
      - persist_to_workspace:
          root: .
          paths:
            - ./public/assets
            - ./config/*.yml

  test1:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - *git-submodules
      - *restore-bundler-cache
      - *restore-npm-cache
#      - *restore-gateway-cache
      - run:
          name: Run tests 1
          command: MULTIJOB_KIND=1 make test-no-deps
      - *store-junit-test-results
      - *store-test-artifacts

  lint:
    docker:
      - image: quay.io/gsaslis/3scale-system-builder
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: circleci
      - image: memcached:1.5-alpine
      - image: redis:4.0-alpine
    steps:
      - run:
          name: Start Xvfb
          command: Xvfb :99 -screen 0 1280x1024x24
          background: true
      - checkout
      - *git-submodules
      - *attach-to-workspace
      - *restore-bundler-cache
      - *restore-npm-cache
      - run:
          name: Licences check
          command: bundle exec rake ci:license_finder:run
      - run:
          name: Swagger validation
          command: |
            bundle exec rake doc:swagger:validate:all
            bundle exec rake doc:swagger:generate:all
      - run:
          name: JSPM
          command: |
            bundle exec rake ci:jspm --trace
      - run:
          name: Yarn test
          command: |
            yarn test -- --reporters dots,junit --browsers Firefox
            yarn jest
      - run:
          name: Database setup
          command: |
            bundle exec rake db:create db:purge db:setup
      - *store-junit-test-results
      - *store-test-artifacts

  unit:
    docker:
      - image: quay.io/gsaslis/3scale-system-builder
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: circleci
      - image: memcached:1.5-alpine
      - image: redis:4.0-alpine
    steps:
      - checkout
      - *git-submodules
      - *attach-to-workspace
      - *restore-bundler-cache
      - *restore-npm-cache
      - run:
          name: Prepare database & config files
          command: |
            cp config/examples/*.yml config/
            bundle exec rake db:create db:test:prepare
      - run:
          name: Rails tests
          command: |
            TESTS=$(bundle exec rake "test:files:$CIRCLE_JOB" | circleci tests split --split-by=timings)
            bundle exec rake test:run TESTS="$TESTS" TESTOPTS=--verbose --verbose --trace
      - *store-junit-test-results
      - *store-test-artifacts
  functional:
    docker:
      - image: quay.io/gsaslis/3scale-system-builder
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: circleci
      - image: memcached:1.5-alpine
      - image: redis:4.0-alpine
    steps:
      - checkout
      - *git-submodules
      - *attach-to-workspace
      - *restore-bundler-cache
      - *restore-npm-cache
      - run:
          name: Prepare database & config files
          command: |
            cp config/examples/*.yml config/
            bundle exec rake db:create db:test:prepare
      - run:
          name: Rails tests
          command: |
            TESTS=$(bundle exec rake "test:files:$CIRCLE_JOB" | circleci tests split --split-by=timings)
            bundle exec rake test:run TESTS="$TESTS" TESTOPTS=--verbose --verbose --trace
          environment:
            LC_ALL: en_US.UTF-8
      - *store-junit-test-results
      - *store-test-artifacts
  integration:
    docker:
      - image: quay.io/gsaslis/3scale-system-builder
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: circleci
      - image: memcached:1.5-alpine
      - image: redis:4.0-alpine
    steps:
      - checkout
      - *git-submodules
      - *attach-to-workspace
      - *restore-bundler-cache
      - *restore-npm-cache
      - run:
          name: Prepare database & config files
          command: |
            cp config/examples/*.yml config/
            bundle exec rake db:create db:test:prepare
      - run:
          name: Rails tests
          command: |
            TESTS=$(bundle exec rake "test:files:$CIRCLE_JOB" | circleci tests split --split-by=timings)
            bundle exec rake test:run TESTS="$TESTS" TESTOPTS=--verbose --verbose --trace
      - *store-junit-test-results
      - *store-test-artifacts
  rspec:
    docker:
      - image: quay.io/gsaslis/3scale-system-builder
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: circleci
      - image: memcached:1.5-alpine
      - image: redis:4.0-alpine
    steps:
      - checkout
      - *git-submodules
      - *attach-to-workspace
      - *restore-bundler-cache
      - *restore-npm-cache
      - run:
          name: Prepare database & config files
          command: |
            cp config/examples/*.yml config/
            bundle exec rake db:create db:test:prepare
      - run:
          name: Rspec tests
          command: |
            bundle exec rspec --format progress $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - *store-junit-test-results
      - *store-test-artifacts

  cucumber:
    docker:
      - image: quay.io/gsaslis/3scale-system-builder
      - image: circleci/mysql:5.7-ram
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: circleci
      - image: memcached:1.5-alpine
      - image: redis:4.0-alpine
    steps:
      - checkout
      - *git-submodules
      - *attach-to-workspace
      - *restore-bundler-cache
      - *restore-npm-cache
      - run:
          name: Prepare database
          command: |
            bundle exec rake db:create db:test:prepare
      - run:
          name: Run cucumber tests
          command: |
            TESTS=$(circleci tests glob "features/**/*.feature" | circleci tests split --split-by=timings)
            # use local dns that points everything to localhost
            sudo sed -c -i"bak" 's/127\.0\.0\.11$/127.0.0.1/' /etc/resolv.conf
            bundle exec cucumber --backtrace --verbose --format junit --out tmp/junit/cucumber --format progress ${TESTS}
      - *store-junit-test-results
      - *store-test-artifacts

workflows:
  version: 2
  parallel_build:
    jobs:
      - dependencies_bundler
      - dependencies_npm
#      - dependencies_apicast
      - assets_precompile:
          requires:
            - dependencies_bundler
            - dependencies_npm
#            - dependencies_apicast

      - lint:
          requires:
            - assets_precompile
      - unit:
          requires:
            - dependencies_bundler
      - functional:
          requires:
            - dependencies_bundler
      - integration:
          requires:
            - assets_precompile
      - rspec:
          requires:
            - dependencies_bundler
      - cucumber:
          requires:
            - assets_precompile
