<% std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --tags ~@wip #{ENV['CUCUMBER_OPTIONS']} -r features" %>
default: <%= std_opts %> features
parallel: --backtrace --format junit --out tmp/junit/cucumber-<%= [ENV['MULTIJOB_KIND'], Process.pid].compact.join('-') %>  --format ParallelTests::Cucumber::FailuresLogger --out tmp/junit/cucumber_<%= ENV['MULTIJOB_KIND'] %>_failures.log --strict --tags ~@wip -r features --format progress
<% tags = %w[ @backend @emails @stats @search @no-txn @javascript ] %>
ci: --backtrace --strict --verbose --format junit --out tmp/junit/cucumber --format progress
txn: --tags=~@wip <%= tags.map { |tag| "--tags=~#{tag}" }.join(' ') %>
no-txn: --tags=~@wip,~@ignore --tag=<%= tags.join(',') %>
list: --dry-run --format Cucumber::Formatter::List
